language: cpp
dist: bionic
os:
  - linux

arch:
  - amd64
  - arm64
  - ppc64le

env:
  - CC=gcc-9 GCOV=gcov-9
  - CC=gcc-8 GCOV=gcov-8
  - CC=clang-7 GCOV='llvm-cov gcov'
  - CC=clang-8 GCOV='llvm-cov gcov'
  - CC=clang-9 GCOV='llvm-cov gcov'
  - CXX=g++-9 GCOV=gcov-9
  - CXX=g++-8 GCOV=gcov-8
  - CXX=clang++-7 GCOV='llvm-cov gcov'
  - CXX=clang++-8 GCOV='llvm-cov gcov'
  - CXX=clang++-9 GCOV='llvm-cov gcov'


before_install:
  - mkdir -p ~/.local/bin
  - eval "${MATRIX_EVAL}"
  - eval "PATH=$PATH:~/.local/bin"
  - pushd /tmp
  - git clone https://github.com/ninja-build/ninja.git
  - cd ninja
  - python3 ./configure.py --bootstrap
  - cp ninja ~/.local/bin/
  - popd
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7.0 main" -y
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8.0 main" -y
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9.0 main" -y

install:
  - sudo apt-get install python3 -y
  - sudo apt-get install python3-pip -y
  - sudo apt-get install python3-setuptools -y

  - sudo apt-get install g++-8 -y
  - sudo apt-get install g++-9 -y
  - sudo apt-get install clang-7 -y
  - sudo apt-get install clang-8 -y
  - sudo apt-get install clang-9 -y

  - sudo apt-get install pkg-config -y
  - sudo apt-get install zlib1g-dev -y
  - sudo apt-get install libncursesw5-dev -y

  - pip3 install --user wheel
  - pip3 install --user meson
  - pip3 install --user codecov

script:
  - meson -Db_coverage=true -Db_sanitize=address,undefined build
  - ninja -C build
  - ninja -C build test

after_success:
  - cd build
  - codecov --gcov-exec "$GCOV"
